Introducing support for Contexts (Config, Secret,Yaml, SecretYaml)
codefresh-io/terraform-provider-codefresh pull request #27
Opened 2020-12-22 21:41 UTC by sandrogattuso

Adding support to manage "Shared Configuration" for both resource and data source.
Supported contexts:

- config
- secret
- yaml
- secret-yaml

2021-01-22 21:14 UTC, logicbomb421 commented
Would love to see this released soon!

2021-01-25 17:12 UTC, logicbomb421 requested changes
Checked this out and ran it locally and noticed a few issues with context names that include spaces. Not entirely sure if this is an issue in the CF API, as `+` _is_ often recognized as encoding for a space, but does not seem to work here. The suggested fix handles spaces using standard url encoding, which does work.

2021-01-25 17:12 UTC, logicbomb421 commented on client/context.go
> +	fullPath := fmt.Sprintf("/contexts/%s?decrypt=true", url.QueryEscape(name))
```suggestion
	fullPath := fmt.Sprintf("/contexts/%s?decrypt=true", url.PathEscape(name))
```
Using `QueryEscape` here produces odd results when `name` contains spaces. For example, `My Context/Other Piece' becomes `My+Context%2FOther+Piece`, which seems to return an HTTP 500 (confirmed via direct API call).

Using `PathEsacpe`, however, produces `My%20Context%2FOther%20Piece`, which _does_ return the context (and HTTP 200).

2021-01-25 17:12 UTC, logicbomb421 commented on client/context.go
> +	fullPath := fmt.Sprintf("/contexts/%s", url.QueryEscape(context.Metadata.Name))
```suggestion
	fullPath := fmt.Sprintf("/contexts/%s", url.PathEscape(context.Metadata.Name))
```
Same reasoning here.

2021-01-25 17:12 UTC, logicbomb421 commented on client/context.go
> +	fullPath := fmt.Sprintf("/contexts/%s", url.QueryEscape(name))
```suggestion
	fullPath := fmt.Sprintf("/contexts/%s", url.PathEscape(name))
```
Same reasoning here.

2021-01-26 00:37 UTC, sandrogattuso commented
> Checked this out and ran it locally and noticed a few issues with context names that include spaces. Not entirely sure if this is an issue in the CF API, as `+` _is_ often recognized as encoding for a space, but does not seem to work here. The suggested fix handles spaces using standard url encoding, which does work.

@logicbomb421 definitely not an issue with the API, not sure how I decided to use the QueryEscape function instead of the PathEscape. The value definitely belongs to the path, 100% agree with your feedback and the suggested changes.
I will push an update shortly and I'll also add a test case that contains special characters to validate this type of scenario.
Thanks for taking the time to provide the above input, really appreciated

2021-01-27 09:15 UTC, sandrogattuso commented
@palson-cf also rebased this one, will do further rebase based on which PR is merged first

2021-01-27 21:31 UTC, sandrogattuso commented
@palson-cf rebased again after last merge, this is now ready for review

2021-01-28 06:23 UTC, palson-cf approved these changes

2021-01-28 06:23 UTC, merged